services:
  - type: worker
    name: team-na-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
